version: '3.8'

services:
  whatsapp-app:
    build:
      context: .
    ports:
      - "3001:3000"  # שנה לפי הפורט שהאפליקציה שלך מאזינה עליו
    restart: unless-stopped
    env_file:
      - stack.env
